#!/usr/bin/env python3
"""Backfill pipeline attribution into existing image-ocean2 outputs.

Renames `output/{ts}_{category}_{slug}_s{seed}.{png,json}` pairs to the
new format `{ts}_{model}_{category}_{slug}_s{seed}.{png,json}` and fills
the pipeline attribution fields (`vae`, `scheduler`, `freeu`, aesthetic
scores, `model_repo`, `pipeline_version`) into each JSON sidecar so every
image self-describes how it was created — important for licensing audits
and reproducibility.

Pipeline era is inferred from the timestamp embedded in the filename:

  ts <  20260502-090501  → pre-quality-stack (Euler / stock VAE / no FreeU)
  ts >= 20260502-090501  → post-quality-stack (DPM++ Karras / fp16-fix VAE / FreeU)

Idempotent: files already in the new format are skipped.

Usage:
  python backfill_attribution.py --dry-run    # preview
  python backfill_attribution.py              # apply
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = ROOT / "output"

# Pipeline-era constants — kept in sync with the matching values in generate.py.
SDXL_VAE_REPO = "madebyollin/sdxl-vae-fp16-fix"
FREEU_SDXL = dict(b1=1.3, b2=1.4, s1=0.9, s2=0.2)

PRE_STACK = dict(
    vae="default",
    scheduler="default (EulerDiscreteScheduler)",
    freeu=None,
    aesthetic_score=None,
    negative_aesthetic_score=None,
    pipeline_version=1,
)

POST_STACK = dict(
    vae=SDXL_VAE_REPO,
    scheduler="DPMSolverMultistepScheduler (dpmsolver++, Karras sigmas)",
    freeu=dict(FREEU_SDXL),
    aesthetic_score=6.0,
    negative_aesthetic_score=2.5,
    pipeline_version=2,
)

# First image generated by the post-quality-stack code on 2026-05-02.
PIPELINE_THRESHOLD = "20260502-090501"

KNOWN_CATEGORIES = [
    "whimsical", "nature", "architecture", "portraits", "sci_fi",
    "fantasy", "food", "animals", "vehicles", "abstract", "custom",
]
KNOWN_MODELS = ["sdxl-refined", "sdxl-base", "juggernaut", "flux"]

# How a model name maps to its checkpoint identifier in the JSON sidecar.
MODEL_REPO = {
    "sdxl-refined": "sd_xl_base_1.0.safetensors + sd_xl_refiner_1.0.safetensors",
    "sdxl-base": "sd_xl_base_1.0.safetensors",
    "juggernaut": "Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors",
    "flux": "black-forest-labs/FLUX.1-schnell",
}

OLD_PATTERN = re.compile(r"^(?P<ts>\d{8}-\d{6})_(?P<rest>.+)_s(?P<seed>\d+)$")


def parse_old_stem(stem: str) -> tuple[str, str, str, int] | None:
    """Return (ts, category, slug, seed) for an old-format stem, or None."""
    m = OLD_PATTERN.match(stem)
    if not m:
        return None
    rest = m["rest"]
    # New-format stems have a known model right after the timestamp.
    for model in KNOWN_MODELS:
        if rest.startswith(model + "_"):
            return None
    # Otherwise the next prefix should be a known category. (sci_fi has an
    # underscore so a naive split() would mis-segment it; longest-prefix match
    # is safer and handles all known categories cleanly.)
    for cat in sorted(KNOWN_CATEGORIES, key=len, reverse=True):
        prefix = cat + "_"
        if rest.startswith(prefix):
            slug = rest[len(prefix):]
            return m["ts"], cat, slug, int(m["seed"])
    return None


def is_new_format(stem: str) -> bool:
    """A stem is already in new format if its second field is a known model name."""
    parts = stem.split("_", 2)
    return len(parts) >= 2 and parts[1] in KNOWN_MODELS


def era_attribution(ts: str) -> dict:
    return dict(POST_STACK) if ts >= PIPELINE_THRESHOLD else dict(PRE_STACK)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dry-run", action="store_true",
                   help="Show what would change without modifying anything.")
    p.add_argument("--out", type=Path, default=OUTPUT_DIR,
                   help="Directory of PNG/JSON pairs.")
    args = p.parse_args(argv)

    if not args.out.exists():
        print(f"ERROR: {args.out} does not exist", file=sys.stderr)
        return 1

    pngs = sorted(args.out.glob("*.png"))
    print(f"Scanning {len(pngs)} PNGs in {args.out}/", flush=True)

    counters = {
        "renamed": 0,
        "already_new": 0,
        "unparseable": 0,
        "missing_json": 0,
        "collision": 0,
        "json_unreadable": 0,
    }

    for png in pngs:
        stem = png.stem

        if is_new_format(stem):
            counters["already_new"] += 1
            continue

        parsed = parse_old_stem(stem)
        if parsed is None:
            counters["unparseable"] += 1
            print(f"  SKIP unparseable: {png.name}", flush=True)
            continue
        ts, category, slug, seed = parsed

        json_path = png.with_suffix(".json")
        if not json_path.exists():
            counters["missing_json"] += 1
            print(f"  SKIP missing JSON: {png.name}", flush=True)
            continue

        try:
            meta = json.loads(json_path.read_text())
        except Exception as e:
            counters["json_unreadable"] += 1
            print(f"  SKIP unreadable JSON ({e}): {png.name}", flush=True)
            continue

        model = meta.get("model") or "sdxl-refined"  # safety default
        attribution = era_attribution(ts)
        new_meta = dict(meta)
        for k, v in attribution.items():
            new_meta.setdefault(k, v)
        new_meta.setdefault("model_repo", MODEL_REPO.get(model, "unknown"))

        new_stem = f"{ts}_{model}_{category}_{slug}_s{seed}"
        new_png = args.out / f"{new_stem}.png"
        new_json = args.out / f"{new_stem}.json"

        if new_png.exists() or new_json.exists():
            counters["collision"] += 1
            print(f"  SKIP collision: {new_stem}", flush=True)
            continue

        if args.dry_run:
            counters["renamed"] += 1
            continue

        # Write JSON first to its OLD path (so a crash mid-rename leaves a coherent
        # pair behind), then rename JSON, then rename PNG.
        json_path.write_text(json.dumps(new_meta, indent=2))
        json_path.rename(new_json)
        png.rename(new_png)
        counters["renamed"] += 1

    print("\nSummary:", flush=True)
    for k, v in counters.items():
        print(f"  {k:<18} {v}", flush=True)
    if args.dry_run:
        print("(dry-run — nothing was modified)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
